server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#    url: jdbc:postgresql://192.168.99.100:15432/chainplusplus
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#  liquibase:
#    user: postgres
#    password: postgres
#    change-log: classpath:liquibase/db.changelog-master.xml
#    url: jdbc:postgresql://192.168.99.100:15432/chainplusplus